version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    container_name: backend-demo
    ports:
    - "51773:1972"
    - "52773:52773"
    volumes:
    - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    container_name: frontend-demo
    ports:
    - "4200:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- ./frontend:/app
    #- /app/node_modules
    
    # workaround to Docker issue https://github.com/moby/moby/issues/38564
    volumes:
    - ./frontend/e2e:/app/e2e
    - ./frontend/src:/app/src
